services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./tools/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./tools/certs/mosquitto:/mosquitto/config/certs
    restart: unless-stopped

  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    container_name: splunk
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    volumes:
      - ./output/TA-MQTT:/opt/splunk/etc/apps/TA-MQTT
      - ./.splunk-persist/TA-MQTT-local:/opt/splunk/etc/apps/TA-MQTT/local
      - splunk-var:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-var:
