[author]
email = dodessy@cisco.com

[launcher]
author = Dominique Dessy
description = Multi-broker MQTT add-on for Splunk. Supports anonymous access, username/password, plain TLS, and mutual TLS (mTLS) with optional client certificates and skip-verify mode.
version = 2.0.1

[package]
id = TA-MQTT
check_for_updates = true

[ui]
is_visible = true
label = MQTT Broker Add-on for Splunk

[triggers]
reload.ta_mqtt_mqtt_broker = simple
reload.ta_mqtt_settings = simple

[id]
version = 2.0.1
name = TA-MQTT

[install]
build = 1773675071
is_configured = false
state = enabled
