[admin:TA_MQTT_configuration]
match = /
members = TA_MQTT_mqtt_broker, TA_MQTT_settings

[admin:TA_MQTT_inputs]
match = /
members = TA_MQTT_mqtt_subscriber

[admin_external:TA_MQTT_mqtt_broker]
handlertype = python
python.version = python3
handlerfile = TA_MQTT_rh_mqtt_broker.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_MQTT_settings]
handlertype = python
python.version = python3
handlerfile = TA_MQTT_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_MQTT_mqtt_subscriber]
handlertype = python
python.version = python3
handlerfile = TA_MQTT_rh_mqtt_subscriber.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
