[expose:TA_MQTT_mqtt_broker]
pattern = TA_MQTT_mqtt_broker
methods = POST, GET

[expose:TA_MQTT_mqtt_broker_specified]
pattern = TA_MQTT_mqtt_broker/*
methods = POST, GET, DELETE

[expose:TA_MQTT_settings]
pattern = TA_MQTT_settings
methods = POST, GET

[expose:TA_MQTT_settings_specified]
pattern = TA_MQTT_settings/*
methods = POST, GET, DELETE

[expose:TA_MQTT_mqtt_subscriber]
pattern = TA_MQTT_mqtt_subscriber
methods = POST, GET

[expose:TA_MQTT_mqtt_subscriber_specified]
pattern = TA_MQTT_mqtt_subscriber/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
