[author]
email = dodessy@cisco.com

[launcher]
author = Dominique Dessy
description = Multi-broker MQTT Add-on for Splunk — supports anonymous, user/password, TLS and mTLS.
version = 2.4.0

[package]
id = TA-MQTT
check_for_updates = false

[ui]
is_visible = 1
label = MQTT Broker Add-on

[triggers]
reload.ta_mqtt_mqtt_broker = simple
reload.ta_mqtt_settings = simple
