# TA-MQTT — props for the mqtt:message sourcetype

[mqtt:message]
SHOULD_LINEMERGE = false
LINE_BREAKER     = ([\r\n]+)
TIME_FORMAT      = %s
KV_MODE          = json

# Extract all top-level JSON keys as fields
INDEXED_EXTRACTIONS = json

# CIM field aliases (IoT / Network Traffic model)
FIELDALIAS-dest = host AS dest
FIELDALIAS-dest_port = port AS dest_port
